// 82-check.mjs —— #82 仓务增量批验收闸（D-129③/D-130②③/D-131③/D-132④/D-133②）
// A=gen-adr-index 生成式索引面 / B=dist 体积棘轮+check-dist 两减痛件 / C=first-external-contributor 触发器 / D=#80 票面勘误两处 / E=幂等再跑
// 用法：node 82-check.mjs（须先 npm run build——dist 实物被棘轮断言）
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');
const ENG = join(REPO, 'engine');
const NL = String.fromCharCode(10);
const CLEAN_ENV = Object.assign({}, process.env, { NODE_OPTIONS: '' });

let pass = 0, fail = 0;
function t(name, ok, detail) { if (ok) { pass++; console.log('PASS ' + name); } else { fail++; console.log('FAIL ' + name + (detail ? ' :: ' + String(detail).slice(0, 260) : '')); } }
function txt(p) { return readFileSync(p, 'utf8'); }

// ---------- A. gen-adr-index 生成式索引（D-130②） ----------
const genScript = join(ENG, 'scripts', 'gen-adr-index.mjs');
const idxFile = join(REPO, 'docs', 'adr', 'README.md');
t('A1 gen-adr-index.mjs 脚本在且挂 npm gen 链', existsSync(genScript) && JSON.parse(txt(join(ENG, 'package.json'))).scripts.gen.indexOf('gen-adr-index.mjs') >= 0);
t('A2 docs/adr/README.md 实物在且带 GENERATED 注记', existsSync(idxFile) && txt(idxFile).indexOf('GENERATED by engine/scripts/gen-adr-index.mjs') >= 0 && txt(idxFile).indexOf('do not edit by hand') >= 0);
const idxBody = existsSync(idxFile) ? txt(idxFile) : '';
// F1 返修：原正则 \[ADR-\d{4}\] 被模板串烹煮成 [ADR-d{4}] 字符类（517 假命中）——
//   改真值对账：索引行数 == docs/adr 下 NNNN-*.md 实物文件数（vacuity 纪律：断言锚实物非自足阈值）。
const adrFileCount = readdirSync(join(REPO, 'docs', 'adr')).filter(function (f) { return /^\d{4}-.+\.md$/.test(f); }).length;
const rows = (idxBody.match(/\[ADR-\d{4}\]/g) || []).length;
t('A3 索引行数==ADR 实物文件数且 ADR-0022/0023 在册（旧区间枚举已消灭）', rows === adrFileCount && rows >= 23 && idxBody.indexOf('[ADR-0022]') >= 0 && idxBody.indexOf('[ADR-0023]') >= 0, 'rows=' + rows + ' files=' + adrFileCount);
const rd = txt(join(REPO, 'README.md'));
t('A4 README 仓图行指向生成式索引且不再裸枚举区间', rd.indexOf('docs/adr/README.md') >= 0 && rd.indexOf('ADR-0001 ~ ADR-0021') < 0);

// ---------- B. dist 体积棘轮 + check-dist 两减痛件（D-129③） ----------
const cd = join(ENG, 'scripts', 'check-dist.mjs');
t('B1 check-dist.mjs 棘轮脚本在且载版本化上限常量', existsSync(cd) && txt(cd).indexOf('DIST_CLI_SIZE_CAP_BYTES') >= 0);
const ci = txt(join(REPO, '.github', 'workflows', 'engine-ci.yml'));
t('B2 rebuild-diff 链挂棘轮调用', ci.indexOf('node scripts/check-dist.mjs') >= 0);
t('B3 rebuild-diff 链载 --ignore-space-at-eol（行尾空白容忍件）', ci.indexOf('--ignore-space-at-eol') >= 0);
t('B4 失败工件上传件在且收窄（steps.rebuilddiff.outcome==failure + upload-artifact + retention；#83 F7j 步级化——job 级 failure() 已收）', ci.indexOf('actions/upload-artifact') >= 0 && ci.indexOf("steps.rebuilddiff.outcome == 'failure'") >= 0 && ci.indexOf('retention-days') >= 0 && ci.indexOf('if: failure()') < 0);
try {
  const out = execFileSync('node', [cd], { encoding: 'utf8', timeout: 60000, env: CLEAN_ENV, cwd: ENG });
  t('B5 棘轮实跑 PASS（dist/cli.js 未越限）', out.indexOf('DIST-RATCHET PASS') >= 0, out.trim());
} catch (e) { t('B5 棘轮实跑 PASS', false, String(e).slice(0, 200)); }

// ---------- C. first-external-contributor 触发器入册（D-130③） ----------
let reg = null;
try { reg = JSON.parse(txt(join(HERE, '33-gate-registry.json'))); } catch (e) { }
const ev = reg && reg.events ? reg.events['first-external-contributor'] : null;
t('C1 事件登记 occurred=false（事件未发生如实）', !!ev && ev.occurred === false);
t('C2 事件注记如实标注仓内自创机制+外部贡献者群体=0', !!ev && typeof ev.note === 'string' && ev.note.indexOf('本仓自创机制') >= 0 && ev.note.indexOf('=0') >= 0);

// ---------- D. #80 票面勘误两处（D-131③/D-132④） ----------
const bl = txt(join(REPO, '.scratch', 'architecture-recovery', 'BACKLOG.md'));
t('D1 golden 锁面枚举对齐 manifest 自声明（语义不变量定点值枚举在票面）', bl.indexOf('语义不变量定点值（枚举对齐 manifest 自声明') >= 0 && bl.indexOf('血缘载荷键集') >= 0);
t('D2 D-038 位点类比措辞勘误在票面（非字面接入+谓词判据）', bl.indexOf('D-038 为位点类比非字面接入') >= 0 && bl.indexOf('落点谓词=谁消费它') >= 0);
t('D3 两处勘误标记者为票面勘误（D-025 纪律——非静默改骨架）', bl.indexOf('D-132④ 票面勘误') >= 0 && bl.indexOf('D-131③ 票面勘误') >= 0);

// ---------- E. 幂等再跑（生成器确定性） ----------
try {
  const before = readFileSync(idxFile);
  execFileSync('node', [genScript], { encoding: 'utf8', timeout: 60000, env: CLEAN_ENV, cwd: ENG });
  const after = readFileSync(idxFile);
  t('E1 gen-adr-index 幂等（重跑字节一致）', Buffer.compare(before, after) === 0);
} catch (e) { t('E1 gen-adr-index 幂等', false, String(e).slice(0, 200)); }

console.log('82CHECK ' + pass + '/' + (pass + fail));
process.exit(fail === 0 ? 0 : 1);
