// demo/demo.ts — 演示入口管线（D-038②③ / A-050 / #45）
// 链 = definition 装载（engine/fixtures/definitions/*.json）
//   → 临时目录生成确定性合成 git 仓（fixture-generator，跑完即弃不污染仓内状态）
//   → Repo Intake 本地腿（D-013：repoAdd/classifyRepoInput——不设新输入面）
//   → 采集（adr-structure@v2 + gitlog + positioning，确定性三族，不接 LLM/不上游二进制）
//   → 裁决（PC/TC/NC，阈值与 reports/22-criteria-pre-registration.md 预声明同源）
//   → 报告（generate.ts buildReport + CASRAI 式 preview_disclosure——D-037② 统一契约面，
//      字段集与 #38 同一契约，禁止两处手抄）
//   → failure 场景确定性触发 degradeReport（降级变体一等演示，D-038 约束列）
// 合成诚实纪律：披露块四印记逐字机读——fixture: synthetic (generated by fixture-generator@1.0.0)
//   ｜not an audit of any real repository｜capability 1 of 5 · preview｜supply-chain: ⚠ unverified。

import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { collectAdrStructureV2, collectAdrStructure, collectGitlog, collectPositioning, deriveBaggageId, sha256Hex, ADR_FIVE_PIECE } from '../collect/collectors.js';
import type { CollectContext, CollectedFact } from '../collect/collectors.js';
import { buildReport, degradeReport, renderMarkdown, renderSidecar, deriveOverallBand, ADJUDICATION_PROTOCOL_VERSION, UNVERIFIED_MARK, REPORT_SKELETON_VERSION } from '../report/generate.js';
import type { PreviewDisclosure, ReportInput, EvidenceItem, ClaimAnchor, QuadrantEntry, Recommendation, AdjudicationEntry } from '../report/generate.js';
import { repoAdd } from '../intake/intake.js';
import { generateFixtureRepo, FIXTURE_GENERATOR_ID } from './fixture-generator.js';
import type { FixtureDefinition } from './fixture-generator.js';

export const DEMO_SCENARIOS: readonly string[] = ['happy-path', 'degraded-supply', 'degraded-incomplete'];
const NL = String.fromCharCode(10);
const DEFINITIONS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'fixtures', 'definitions');

// ---------- 预声明阈值（与 reports/22-criteria-pre-registration.md 逐字同源，跑后禁调） ----------
const TC1_LAG_DAYS = 90;
const TC1_RATIO_RED = 0.20;
const TC1_MIN_N = 5;
const TC2_MEAN_RED = 0.60;
const TC2_FIELD_MISSING_RED = 0.50;
const TC3_RED = 0.50;
const TC3_GREEN = 0.70;
const TC3_TOPN = 20;
// stopwords 与 22-threshold-raw.json#tc3_s1_coverage.stopwords 同源快照（fixture 管线自含，不读 .scratch）
const DEMO_STOPWORDS: readonly string[] = ['the', 'and', 'for', 'with', 'that', 'this', 'from', 'into', 'per', 'via', 'not', 'all', 'any', 'are', 'was', 'were', 'has', 'have', 'had', 'its', 'but', 'can', 'may', 'our', 'out', 'over', 'under', 'when', 'which', 'will', 'would', 'should', 'must', 'such', 'than', 'then', 'they', 'them', 'their', 'there', 'here', 'each', 'both', 'same', 'more', 'most', 'some', 'only', 'also', 'been', 'being', 'does', 'did', 'done', '的', '了', '是', '在', '和', '与', '及', '或', '为', '以', '对', '从', '到', '被', '把', '给', '让', '使', '等', '就', '都', '也', '还', '很', '更', '最', '要', '会', '能', '可', '将', '已', '未', '无', '非', '个', '中', '上', '下', '之', '其', '此', '该', '由', '而', '但', '则', '若', '如', '于', '所', '有', '这', '那', '不', '一', '二', '三', '的的', '了的', '是在', '和的', '与的', '为的', '对的', '中的', '上的', '下的', '之中', '一个', '这个', '那个', '我们', '他们', '可以', '因为', '所以', '但是', '如果', '通过', '进行', '以及', '并且', '从而', '因此', '其中', '对应', '相关', '分别', '同时', '之后', '之前', '以内', '以上', '以下'];
const INTENT_CANDIDATES: readonly string[] = ['CONTEXT.md', 'README.md', 'AGENTS.md'];
const NC1_CANDIDATES: readonly string[] = ['package.json', 'README.md', 'Cargo.toml'];

// ---------- 正/负对照夹具（与 39-macro-b-one-shot.mjs 同构；管线健康闸与被测仓无关） ----------
const GOLDEN_ADR = [
  '# ADR-9999: PC-1 golden fixture',
  '',
  '- Status: accepted',
  '- Date: 2026-09-13',
  '- Deciders: fixture',
  '- Ledger: D-000',
  '',
  '## Context',
  '',
  'fixture context.',
  '',
  '## Decision',
  '',
  'fixture decision.',
  '',
  '## Consequences',
  '',
  'fixture consequences; this supersedes ADR-0000.'
].join(NL);
const POS_DECL = 'macro audit positioning convergence determinism traceability provenance fact table skeleton slice quadrant scale verdict gate receipt citation anchor';

// ---------- CASRAI 式披露块（D-038③ 四印记逐字；复用 preview_disclosure 同一字段契约——统一契约面禁两处手抄） ----------
export function demoDisclosure(): PreviewDisclosure {
  return {
    capability_label: 'capability 1 of 5 · preview',
    calibration_scope: 'fixture: synthetic (generated by ' + FIXTURE_GENERATOR_ID + ')',
    structural_limitations: [
      'not an audit of any real repository——合成 fixture 仓演示产物，所有裁定不构成真实审计结论（D-038 硬契约：合成数据不冒充真实审计）',
      'supply-chain: ' + UNVERIFIED_MARK + '——Scorecard/repomix 未接入，供应链象限证据缺失（D-034③④ 演示化维持）',
      'structure/behavior/supply_chain 象限 not_applicable：Macro-B 已上架采集面仅 strategy（S1+S2）',
      '确定性 fixture：同 scenario 重跑产物逐字节一致（pin author/committer/date）；临时目录生成跑完即弃不污染仓内状态'
    ],
    not_in_preview: ['Micro-A', 'Micro-B', 'Macro-A']
  };
}

export function listScenarios(): { scenarios: { name: string; description: string; expect: FixtureDefinition['expect'] }[] } {
  const out: { name: string; description: string; expect: FixtureDefinition['expect'] }[] = [];
  for (const name of DEMO_SCENARIOS) {
    const def = loadDefinition(name);
    out.push({ name: name, description: def.description, expect: def.expect });
  }
  return { scenarios: out };
}

export function loadDefinition(scenario: string): FixtureDefinition {
  if (DEMO_SCENARIOS.indexOf(scenario) < 0) {
    throw new Error('DEMO-SCENARIO-UNKNOWN: ' + scenario + '（可选：' + DEMO_SCENARIOS.join(' / ') + '）');
  }
  const p = join(DEFINITIONS_DIR, scenario + '.json');
  if (!existsSync(p)) { throw new Error('DEMO-DEFINITION-MISSING: ' + p); }
  const def = JSON.parse(readFileSync(p, 'utf8')) as FixtureDefinition;
  if (def.scenario !== scenario) { throw new Error('DEMO-DEFINITION-MISMATCH: 文件 ' + scenario + '.json 内 scenario=' + def.scenario); }
  return def;
}

export interface DemoOptions {
  scenario?: string;
  outDir?: string;      // 指定则写 4 件产物；缺省只在内存渲染（stdout 打印由 CLI 决定）
  keepTemp?: boolean;   // 保留临时 fixture 仓（调试位；默认跑完即弃）
  tempRoot?: string;    // 测试注入位；默认 os.tmpdir()
}

export interface DemoResult {
  scenario: string;
  synthetic: true;
  verdict: string;
  degraded_mode: boolean;
  degraded_reason: string | null;
  receipt_id: string;
  head_sha: string;
  commit_count: number;
  adr_count: number;
  fact_count: number;
  intake_kind: string;
  temp_dir: string | null;
  temp_discarded: boolean;
  out_dir: string | null;
  artifacts: { report_md: string; report_json: string; measurements: string; facts: string } | null;
  report_markdown: string;
  sidecar_json: string;
  measurements: Record<string, unknown>;
}

function git(root: string, args: readonly string[]): string {
  return execFileSync('git', ['-C', root].concat(args as string[]), { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 }).trim();
}

function pickExcerpt(absOrRelPath: string, tokens: readonly string[] | null, base: string | null): { line: number; text: string } {
  const text = readFileSync(base ? join(base, absOrRelPath) : absOrRelPath, 'utf8');
  const lines = text.split(NL);
  if (tokens === null) { return { line: 1, text: lines[0].trim() }; }
  for (let i = 0; i < lines.length; i++) {
    let all = true;
    for (const tk of tokens) { if (lines[i].indexOf(tk) < 0) { all = false; } }
    if (all) { return { line: i + 1, text: lines[i].trim() }; }
  }
  throw new Error('EXCERPT-MISS: ' + absOrRelPath + ' tokens=' + String(tokens));
}

export function runDemo(opts: DemoOptions): DemoResult {
  const scenario = opts.scenario || 'happy-path';
  const def = loadDefinition(scenario);
  const tempRoot = opts.tempRoot || tmpdir();
  const workDir = mkdtempSync(join(tempRoot, 'macro-audit-demo-'));
  const repoDir = join(workDir, 'repo');

  try {
    // ---------- §1 临时目录生成确定性合成 git 仓（跑完即弃） ----------
    const gen = generateFixtureRepo(def, repoDir);

    // ---------- §2 Repo Intake 本地腿（D-013：同一输入面，不设新入口） ----------
    const intake = repoAdd(repoDir);
    const HEAD_SHA = intake.head_sha;
    const HEAD_DATE = git(repoDir, ['log', '-1', '--format=%cI']);
    const TREE_SHA = git(repoDir, ['rev-parse', 'HEAD^{tree}']);
    const COMMIT_COUNT = Number(git(repoDir, ['rev-list', '--count', 'HEAD']));
    const ctx: CollectContext = {
      runId: 'r45-' + scenario + '-' + HEAD_SHA.slice(0, 7),
      traceId: sha256Hex(def.repo.name + '|' + HEAD_SHA + '|' + HEAD_DATE).slice(0, 32),
      repoRef: def.repo.name + '@' + HEAD_SHA,
      scale: 'Macro-B',
      observedAt: HEAD_DATE
    };

    // ---------- §3 采集：gitlog（PROBE-INVARIANT 先断言） ----------
    const rawLog = git(repoDir, ['log', '--pretty=format:__R__%H|%an|%cI', '--name-only']);
    const commits: { sha: string; author: string; date: string; paths: string[] }[] = [];
    let cur: { sha: string; author: string; date: string; paths: string[] } | null = null;
    for (const line of rawLog.split(NL)) {
      const t = line.trim();
      if (t.indexOf('__R__') === 0) {
        const parts = t.slice(5).split('|');
        cur = { sha: parts[0], author: parts[1], date: parts[2], paths: [] };
        commits.push(cur);
      } else if (cur && t.length > 0) {
        cur.paths.push(t);
      }
    }
    if (commits.length !== COMMIT_COUNT) { throw new Error('PROBE-INVARIANT-FAIL[' + scenario + ']: parsed ' + commits.length + ' != git rev-list ' + COMMIT_COUNT); }

    // ---------- §4 采集：ADR 语料（adr-structure@v2 回退链） ----------
    const adrDir = join(repoDir, 'docs', 'adr');
    const adrFiles = existsSync(adrDir) ? readdirSync(adrDir).filter(function (f) { return /^\d{3,}.*\.md$/i.test(f); }).sort() : [];
    const firstCommitOf = function (p: string): string | null {
      let best: string | null = null;
      for (const c of commits) { if (c.paths.indexOf(p) >= 0 && (best === null || c.date < best)) { best = c.date; } }
      return best;
    };
    const adrDocs = adrFiles.map(function (f) {
      const rel = 'docs/adr/' + f;
      return { path: rel, text: readFileSync(join(adrDir, f), 'utf8'), first_commit_date: firstCommitOf(rel) };
    });
    const adrPaths = adrDocs.map(function (d) { return d.path; });
    const adrFacts = collectAdrStructureV2({ documents: adrDocs }, ctx);
    const adrDateMap: Record<string, string> = {};
    for (const f of adrFacts) {
      if (f.metric === 'adr.decision_date') {
        const v = JSON.parse(f.value_json);
        if (v.date) { adrDateMap[f.subject_ref] = v.date.slice(0, 10); }
      }
    }
    const gitFacts = collectGitlog({ commits: commits, paths: adrPaths, adrDates: adrDateMap }, ctx);

    // ---------- §5 采集：positioning（意图面=仓根三件套；交付面=git subjects） ----------
    const intentDocs: { path: string; text: string }[] = [];
    for (const cand of INTENT_CANDIDATES) {
      const p = join(repoDir, cand);
      if (existsSync(p)) { intentDocs.push({ path: cand, text: readFileSync(p, 'utf8') }); }
    }
    const subjects = git(repoDir, ['log', '--pretty=format:%s']).split(NL);
    const deliveryDocs = [{ path: 'git log subjects @ ' + HEAD_SHA.slice(0, 7), text: subjects.join(NL) }];
    const posFacts = intentDocs.length > 0
      ? collectPositioning({ intentDocs: intentDocs, deliveryDocs: deliveryDocs, topN: TC3_TOPN, stopwords: DEMO_STOPWORDS }, ctx)
      : [];
    const realFacts: CollectedFact[] = adrFacts.concat(posFacts, gitFacts);

    // ---------- §6 正/负对照（管线健康闸；夹具与被测仓无关） ----------
    const pc1AdrFacts = collectAdrStructure({ documents: [{ path: 'fixtures/45-pc1-golden-adr.md', text: GOLDEN_ADR }] }, ctx);
    const pc1PosFacts = collectPositioning({ intentDocs: [{ path: 'fixtures/45-pc1-positioning.md', text: POS_DECL }], deliveryDocs: [{ path: 'fixtures/45-pc1-delivery.md', text: POS_DECL }], topN: TC3_TOPN, stopwords: DEMO_STOPWORDS }, ctx);
    const pc1Five = pc1AdrFacts.find(function (f) { return f.metric === 'adr.five_piece_completeness'; });
    const pc1Sup = pc1AdrFacts.find(function (f) { return f.metric === 'adr.supersede_link_present'; });
    const pc1 = { pass: pc1AdrFacts.length > 0 && pc1PosFacts.length > 0 && !!pc1Five && JSON.parse(pc1Five.value_json).present === 5 && !!pc1Sup && JSON.parse(pc1Sup.value_json).present === true };
    const PC2_PATH = 'fixtures/45-pc2-lag-adr.md';
    const pc2Commits = [{ sha: 'pc2fixture0000000000000000000000000000045', author: 'fixture', date: '2026-01-01T00:00:00+00:00', paths: [PC2_PATH] }];
    const pc2AdrDates: Record<string, string> = {}; pc2AdrDates[PC2_PATH] = '2026-09-13';
    const pc2Facts = collectGitlog({ commits: pc2Commits, paths: [PC2_PATH], adrDates: pc2AdrDates }, ctx);
    const pc2Lag = pc2Facts.filter(function (f) { return f.metric === 'git.adr_lag_days'; });
    const pc2 = { pass: pc2Lag.length > 0 && JSON.parse(pc2Lag[0].value_json).delta_days > 0, delta_days: pc2Lag.length > 0 ? JSON.parse(pc2Lag[0].value_json).delta_days : null };
    let nc1Path: string | null = null;
    for (const cand of NC1_CANDIDATES) { if (existsSync(join(repoDir, cand))) { nc1Path = cand; break; } }
    if (!nc1Path) { throw new Error('NC1-CANDIDATE-MISS[' + scenario + ']'); }
    const nc1Facts = collectAdrStructure({ documents: [{ path: nc1Path, text: readFileSync(join(repoDir, nc1Path), 'utf8') }] }, ctx);
    const nc1Five = nc1Facts.find(function (f) { return f.metric === 'adr.five_piece_completeness'; });
    const nc1Sup = nc1Facts.find(function (f) { return f.metric === 'adr.supersede_link_present'; });
    const nc1 = { path: nc1Path, fact_count: nc1Facts.length, five_piece_present: nc1Five ? JSON.parse(nc1Five.value_json).present : -1, supersede_present: nc1Sup ? JSON.parse(nc1Sup.value_json).present : null, pass: false };
    nc1.pass = nc1.fact_count > 0 && nc1.five_piece_present === 0 && nc1.supersede_present === false;

    // ---------- §7 真判据 TC-1/TC-2/TC-3（预声明阈值实测） ----------
    const lagValues = gitFacts.filter(function (f) { return f.metric === 'git.adr_lag_days'; }).map(function (f) { return JSON.parse(f.value_json); });
    const tc1Judgeable = lagValues.length;
    const tc1Backfill = lagValues.filter(function (v) { return v.delta_days > TC1_LAG_DAYS; }).length;
    const tc1Ratio = tc1Judgeable === 0 ? 0 : tc1Backfill / tc1Judgeable;
    const tc1Verdict = tc1Judgeable < TC1_MIN_N ? 'INCONCLUSIVE' : (tc1Ratio > TC1_RATIO_RED ? 'RED' : 'NOT_RED');
    const fiveValues = adrFacts.filter(function (f) { return f.metric === 'adr.five_piece_completeness'; }).map(function (f) { return JSON.parse(f.value_json); });
    const tc2Total = fiveValues.length;
    const tc2Mean = tc2Total === 0 ? 0 : fiveValues.reduce(function (s, v) { return s + v.ratio; }, 0) / tc2Total;
    const tc2Missing: Record<string, number> = {};
    for (const k of ADR_FIVE_PIECE) { tc2Missing[k] = 0; }
    for (const v of fiveValues) { for (const k of v.missing) { tc2Missing[k] = tc2Missing[k] + 1; } }
    const tc2MissingRatio: Record<string, number> = {};
    for (const k of Object.keys(tc2Missing)) { tc2MissingRatio[k] = tc2Total === 0 ? 0 : tc2Missing[k] / tc2Total; }
    const tc2CondA = tc2Mean < TC2_MEAN_RED;
    let tc2CondB = false;
    for (const k of Object.keys(tc2MissingRatio)) { if (tc2MissingRatio[k] > TC2_FIELD_MISSING_RED) { tc2CondB = true; } }
    const tc2Verdict = (tc2CondA || tc2CondB) ? 'RED' : 'NOT_RED';
    const covFacts = posFacts.filter(function (f) { return f.metric === 'positioning.keyword_coverage'; }).map(function (f) { return { subject: f.subject_ref, value: JSON.parse(f.value_json), fact_id: f.fact_id }; });
    let tc3Lowest: { subject: string; value: { ratio: number; hit: number; keywords: number }; fact_id: string } | null = null;
    for (const c of covFacts) { if (tc3Lowest === null || c.value.ratio < tc3Lowest.value.ratio) { tc3Lowest = c; } }
    const tc3Ratio = tc3Lowest ? tc3Lowest.value.ratio : 0;
    const tc3Verdict = intentDocs.length === 0 ? 'INCONCLUSIVE' : (tc3Ratio < TC3_RED ? 'RED' : (tc3Ratio < TC3_GREEN ? 'AMBER' : 'GREEN'));

    // ---------- §8 实测数落盘（工件内禁绝对路径——golden 逐字节稳定） ----------
    const measurements = {
      scenario: scenario,
      synthetic: true,
      generator: FIXTURE_GENERATOR_ID,
      observed_at: HEAD_DATE,
      head_sha: HEAD_SHA,
      tree_sha: TREE_SHA,
      commit_count: COMMIT_COUNT,
      merge_commits: gen.merge_commits,
      branches: gen.branches,
      tags: gen.tags,
      adr_count: tc2Total,
      intent_docs: intentDocs.map(function (d) { return d.path; }),
      fact_count: realFacts.length,
      intake: { kind: intake.kind, shallow: intake.shallow, full_depth_verified: intake.full_depth_verified, remote_config_execution: intake.remote_config_execution, credentials: intake.credentials, cloned: intake.cloned },
      tc1: { judgeable_n: tc1Judgeable, backfill_n: tc1Backfill, ratio_4: tc1Ratio.toFixed(4), verdict: tc1Verdict, threshold: { lag_days: TC1_LAG_DAYS, ratio_red: TC1_RATIO_RED, min_n: TC1_MIN_N } },
      tc2: { total: tc2Total, mean_ratio_4: tc2Mean.toFixed(4), missing_counts: tc2Missing, missing_ratio_4: Object.fromEntries(Object.keys(tc2MissingRatio).map(function (k) { return [k, Number(tc2MissingRatio[k].toFixed(4))]; })), cond_a: tc2CondA, cond_b: tc2CondB, verdict: tc2Verdict, threshold: { mean_red: TC2_MEAN_RED, field_missing_red: TC2_FIELD_MISSING_RED } },
      tc3: { per_source: covFacts.map(function (c) { return { path: c.subject, hit: c.value.hit, keywords: c.value.keywords, ratio_4: c.value.ratio.toFixed(4) }; }), lowest_path: tc3Lowest ? tc3Lowest.subject : null, lowest_ratio_4: tc3Ratio.toFixed(4), verdict: tc3Verdict, threshold: { red: TC3_RED, green: TC3_GREEN, top_n: TC3_TOPN } },
      nc1: nc1, pc1: pc1, pc2: pc2,
      failure_trigger: def.failure ? def.failure.trigger : null,
      expect: def.expect
    };

    const outDir = opts.outDir ? resolve(opts.outDir) : join(workDir, 'out');
    mkdirSync(outDir, { recursive: true });
    const MEAS_NAME = 'demo-measurements.json';
    const FACTS_NAME = 'demo-facts.jsonl';
    const MD_NAME = 'report.md';
    const JSON_NAME = 'report.json';
    writeFileSync(join(outDir, MEAS_NAME), JSON.stringify(measurements, null, 2) + NL, 'utf8');
    writeFileSync(join(outDir, FACTS_NAME), realFacts.map(function (f) { return JSON.stringify(f); }).join(NL) + NL, 'utf8');

    // ---------- §9 证据 + 结论→引文锚（源一律相对名——工件零绝对路径） ----------
    const evidence: EvidenceItem[] = [];
    function addEvidence(id: string, source: string, tokens: readonly string[] | null, claim: string, reproCmd: string, base: string | null) {
      const ex = pickExcerpt(source, tokens, base);
      evidence.push({ evidence_id: id, source: source, locator: 'L' + ex.line, claim: claim, grounded: true, collected_at: HEAD_DATE, reproduce_cmd: reproCmd, reproduce_absent_reason: null, required_tokens: [], excerpt: ex.text });
    }
    const RUN_CMD = 'macro-audit demo --scenario ' + scenario;
    const R = scenario.toUpperCase().split('-').join('');
    addEvidence('EV-45-' + R + '-01', MEAS_NAME, ['"fact_count"'], '本次实测：' + scenario + ' 合成 fixture 采集事实数', RUN_CMD, outDir);
    addEvidence('EV-45-' + R + '-02', MEAS_NAME, ['"verdict"'], '本次实测：TC-1 ADR 事后补写判据裁定（' + tc1Verdict + '）', RUN_CMD, outDir);
    addEvidence('EV-45-' + R + '-03', MEAS_NAME, ['"mean_ratio_4"'], '本次实测：TC-2 五件套完整度 mean_ratio', RUN_CMD, outDir);
    addEvidence('EV-45-' + R + '-04', MEAS_NAME, ['"lowest_ratio_4"'], '本次实测：TC-3 定位覆盖率最低值', RUN_CMD, outDir);
    addEvidence('EV-45-' + R + '-05', MEAS_NAME, ['"five_piece_present"'], '本次实测：NC-1 负对照选材五件套命中数（预期 0）', RUN_CMD, outDir);
    if (adrFiles.length > 0) {
      addEvidence('EV-45-' + R + '-06', 'docs/adr/' + adrFiles[0], null, scenario + ' 合成 ADR 语料锚：docs/adr/' + adrFiles[0] + ' 实物存在（语料 ' + adrFiles.length + ' 份，synthetic fixture）', 'git -C <fixture-repo> show HEAD:docs/adr/' + adrFiles[0], repoDir);
    }
    addEvidence('EV-45-' + R + '-07', MEAS_NAME, ['"synthetic": true'], '合成印记：本报告全部语料为 synthetic fixture 生成仓，not an audit of any real repository', RUN_CMD, outDir);

    const claims: ClaimAnchor[] = [
      { claim_id: 'CL-45-' + R + '-01', evidence_id: 'EV-45-' + R + '-01', required_tokens: ['fact_count'] },
      { claim_id: 'CL-45-' + R + '-02', evidence_id: 'EV-45-' + R + '-02', required_tokens: ['verdict'] },
      { claim_id: 'CL-45-' + R + '-03', evidence_id: 'EV-45-' + R + '-03', required_tokens: ['mean_ratio_4'] },
      { claim_id: 'CL-45-' + R + '-04', evidence_id: 'EV-45-' + R + '-04', required_tokens: ['lowest_ratio_4'] },
      { claim_id: 'CL-45-' + R + '-05', evidence_id: 'EV-45-' + R + '-05', required_tokens: ['five_piece_present'] },
      { claim_id: 'CL-45-' + R + '-06', evidence_id: 'EV-45-' + R + '-07', required_tokens: ['synthetic', 'true'] }
    ];

    // ---------- §10 裁决条目（判据 id 与 39 同族；band 三档如实） ----------
    function tcBand(v: string): 'supported' | 'unsupported' | 'insufficient' {
      if (v === 'INCONCLUSIVE') { return 'insufficient'; }
      if (v === 'RED') { return 'unsupported'; }
      return 'supported';
    }
    const GATE_REF = {
      prereg_commit: '45-demo-criteria',
      criteria_path: 'reports/22-criteria-pre-registration.md',
      basis_path: 'reports/22-c-adjudication-basis.md',
      criterion_ids: ['PC-1', 'PC-2', 'TC-1', 'TC-2', 'TC-3', 'NC-1']
    };
    const tc1FactIds = gitFacts.filter(function (f) { return f.metric === 'git.adr_lag_days'; }).map(function (f) { return f.fact_id; });
    const tc2FactIds = adrFacts.filter(function (f) { return f.metric === 'adr.five_piece_completeness'; }).map(function (f) { return f.fact_id; });
    const tc3FactIds = covFacts.map(function (c) { return c.fact_id; });
    const adjudicationEntries: AdjudicationEntry[] = [
      { criterion_id: 'PC-1', band: pc1.pass ? 'supported' : 'insufficient', basis_refs: ['B1'], anchored_fact_ids: [pc1AdrFacts[0].fact_id, pc1PosFacts[0].fact_id], anchored_evidence_ids: ['EV-45-' + R + '-01'], decided_at: HEAD_DATE, rationale: pc1.pass ? 'adr-structure 与 positioning 两族均产出非空事实，golden ADR 五件套 5/5 且 supersede 链命中（合成 run 内管线活性正对照）' : '正对照未中，管线故障 P0' },
      { criterion_id: 'PC-2', band: pc2.pass ? 'supported' : 'insufficient', basis_refs: ['B1'], anchored_fact_ids: pc2Lag.length > 0 ? [pc2Lag[0].fact_id] : [], anchored_evidence_ids: ['EV-45-' + R + '-01'], decided_at: HEAD_DATE, rationale: pc2.pass ? 'gitlog 族检出事后补写 delta_days = ' + String(pc2.delta_days) : '正对照未中，管线故障 P0' },
      { criterion_id: 'TC-1', band: tcBand(tc1Verdict), basis_refs: ['B2'], anchored_fact_ids: tc1FactIds, anchored_evidence_ids: ['EV-45-' + R + '-02'], decided_at: HEAD_DATE, rationale: scenario + ' ADR 事后补写：可判定数 ' + tc1Judgeable + '（门槛 ' + TC1_MIN_N + '），>90d 占比 ' + measurements.tc1.ratio_4 + '，判 ' + tc1Verdict },
      { criterion_id: 'TC-2', band: tcBand(tc2Verdict), basis_refs: ['B2'], anchored_fact_ids: tc2FactIds, anchored_evidence_ids: ['EV-45-' + R + '-03'], decided_at: HEAD_DATE, rationale: scenario + ' ADR 五件套：mean_ratio ' + measurements.tc2.mean_ratio_4 + '（门槛 ' + TC2_MEAN_RED + '），字段缺失率超线=' + tc2CondB + '，判 ' + tc2Verdict },
      { criterion_id: 'TC-3', band: tcBand(tc3Verdict), basis_refs: ['B2'], anchored_fact_ids: tc3FactIds, anchored_evidence_ids: ['EV-45-' + R + '-04'], decided_at: HEAD_DATE, rationale: scenario + ' 定位覆盖：意图面 ' + intentDocs.length + ' 件最低 ratio ' + measurements.tc3.lowest_ratio_4 + '（' + String(measurements.tc3.lowest_path) + '），判 ' + tc3Verdict },
      { criterion_id: 'NC-1', band: nc1.pass ? 'supported' : 'insufficient', basis_refs: ['B4'], anchored_fact_ids: nc1Facts.length > 0 ? [nc1Facts[0].fact_id] : [], anchored_evidence_ids: ['EV-45-' + R + '-05'], decided_at: HEAD_DATE, rationale: nc1.pass ? '负对照选材 ' + nc1Path + ' 五件套 0 命中、supersede 0 命中（特异性成立）' : '负对照命中，转复核路径' }
    ];
    const strategyBand = deriveOverallBand(adjudicationEntries);

    // ---------- §11 四象限 + 建议 + 报告装配（披露块=CASRAI 式统一契约面） ----------
    const GATE = { protocol_version: ADJUDICATION_PROTOCOL_VERSION, audit_ref: 'engine/src/demo/demo.ts' };
    const quadrants: QuadrantEntry[] = [
      { quadrant: 'strategy', applicability: 'native', verdict: strategyBand, score: null, confidence: 0.6, dimensions: ['S1', 'S2'], slice_fields: { s1_keyword_coverage_ratio: Number(measurements.tc3.lowest_ratio_4), s2_five_piece_mean_ratio: Number(measurements.tc2.mean_ratio_4), adr_count: tc2Total, lag_judgeable_n: tc1Judgeable, intent_docs: intentDocs.length }, verdict_gate: { protocol_version: GATE.protocol_version, decision: strategyBand, evidence_threshold_met: tc2Verdict === 'RED', decided_at: HEAD_DATE, override_reason: null, audit_ref: GATE.audit_ref }, conflict_markers: ['synthetic-fixture'] },
      { quadrant: 'structure', applicability: 'not_applicable', verdict: 'insufficient', score: null, confidence: 0, dimensions: [], slice_fields: {}, verdict_gate: { protocol_version: GATE.protocol_version, decision: 'insufficient', evidence_threshold_met: false, decided_at: HEAD_DATE, override_reason: 'Macro-B 已上架采集面仅 strategy（S1+S2）——structure 无采集器（与 #23/#39 同口径）', audit_ref: GATE.audit_ref }, conflict_markers: ['out-of-scope-stage1'] },
      { quadrant: 'behavior', applicability: 'not_applicable', verdict: 'insufficient', score: null, confidence: 0, dimensions: [], slice_fields: {}, verdict_gate: { protocol_version: GATE.protocol_version, decision: 'insufficient', evidence_threshold_met: false, decided_at: HEAD_DATE, override_reason: 'Macro-B 已上架采集面仅 strategy（S1+S2）——behavior 无采集器', audit_ref: GATE.audit_ref }, conflict_markers: ['out-of-scope-stage1'] },
      { quadrant: 'supply_chain', applicability: 'not_applicable', verdict: 'insufficient', score: null, confidence: 0, dimensions: [], slice_fields: {}, verdict_gate: { protocol_version: GATE.protocol_version, decision: 'insufficient', evidence_threshold_met: false, decided_at: HEAD_DATE, override_reason: '⚠ 数据未接——Scorecard/repomix 按层需求队列接入不插队（D-034③）', audit_ref: GATE.audit_ref }, conflict_markers: ['data-not-connected'] }
    ];
    const recommendations: Recommendation[] = [
      { rec_id: 'R-45-' + R + '-1', priority: 'P1', action: '对真实目标仓跑同一链路：`macro-audit repo add <path|url>` 接入后按 Macro-B 口径裁决——本报告为合成 fixture 演示，not an audit of any real repository', rationale: 'D-038 硬契约：合成数据不冒充真实审计结论；本演示只证管线形态与披露面', expected_impact: '获得真实审计结论而非演示数据', effort: 'S', verdict_gate_stamp: ADJUDICATION_PROTOCOL_VERSION + ' / ' + strategyBand, evidence_refs: ['EV-45-' + R + '-07'], degraded_note: null },
      { rec_id: 'R-45-' + R + '-2', priority: 'P3', action: '供应链象限维持「⚠ 数据未接」：Scorecard/repomix 按层需求队列接入不插队（D-034③④）', rationale: 'preview 诚实形态保持——supply-chain: ' + UNVERIFIED_MARK + ' 为披露块常驻印记', expected_impact: '披露诚实性保持', effort: 'S', verdict_gate_stamp: ADJUDICATION_PROTOCOL_VERSION + ' / ' + strategyBand, evidence_refs: ['EV-45-' + R + '-01'], degraded_note: null }
    ];
    const HEADLINE = def.repo.name + ' demo（capability 1 of 5 · preview · synthetic fixture）：' + COMMIT_COUNT + ' commits / ADR ' + tc2Total + ' 份 / facts ' + realFacts.length + '——TC-1 ' + tc1Verdict + '（n=' + tc1Judgeable + '）、TC-2 ' + tc2Verdict + '（mean=' + measurements.tc2.mean_ratio_4 + '）、TC-3 ' + tc3Verdict + '（' + measurements.tc3.lowest_ratio_4 + '）→ 综合裁定 ' + strategyBand + '。not an audit of any real repository——合成语料不冒充真实审计（D-038）。';

    const reportInput: ReportInput = {
      report_id: 'MA-45-DEMO-' + R,
      scale: 'Macro-B',
      subject_ref: def.repo.name + '@' + HEAD_SHA.slice(0, 12),
      generated_at: HEAD_DATE,
      trace_id: ctx.traceId,
      baggage_id: deriveBaggageId(ctx, 'S2'),
      headline: HEADLINE,
      confidence: 0.6,
      stale: { marker: 'fresh', sla_seconds: 5, lag_seconds: 0, read_model_version: REPORT_SKELETON_VERSION, fact_watermark_version: '1' },
      fact_ids: realFacts.map(function (f) { return f.fact_id; }),
      top_findings: ['EV-45-' + R + '-01', 'EV-45-' + R + '-03', 'EV-45-' + R + '-04'],
      evidence: evidence,
      claims: claims,
      quadrants: quadrants,
      recommendations: recommendations,
      adjudication_entries: adjudicationEntries,
      decided_at: HEAD_DATE,
      commit_anchor: HEAD_SHA,
      tree_anchor: TREE_SHA,
      gate_ref: GATE_REF,
      degraded: false,
      degraded_reason: null,
      preview_disclosure: demoDisclosure(),
      human: { status: 'pending', adjudicator: 'user', text: null, decided_at: null }
    };
    let report = buildReport(reportInput);

    // ---------- §12 失败路径一等演示：definition.failure 确定性触发降级产出 ----------
    if (def.failure) {
      report = degradeReport(report, def.failure.reason);
    }

    const reportMd = renderMarkdown(report) + NL;
    const sidecarJson = renderSidecar(report) + NL;
    writeFileSync(join(outDir, MD_NAME), reportMd, 'utf8');
    writeFileSync(join(outDir, JSON_NAME), sidecarJson, 'utf8');

    const artifacts = { report_md: join(outDir, MD_NAME), report_json: join(outDir, JSON_NAME), measurements: join(outDir, MEAS_NAME), facts: join(outDir, FACTS_NAME) };
    const result: DemoResult = {
      scenario: scenario,
      synthetic: true,
      verdict: report.overall_verdict,
      degraded_mode: report.degraded_mode,
      degraded_reason: report.degraded_reason,
      receipt_id: report.receipt.receipt_id,
      head_sha: HEAD_SHA,
      commit_count: COMMIT_COUNT,
      adr_count: tc2Total,
      fact_count: realFacts.length,
      intake_kind: intake.kind,
      temp_dir: opts.keepTemp ? workDir : null,
      temp_discarded: !opts.keepTemp,
      out_dir: opts.outDir ? outDir : null,
      artifacts: opts.outDir ? artifacts : null,
      report_markdown: reportMd,
      sidecar_json: sidecarJson,
      measurements: measurements
    };
    return result;
  } finally {
    if (!opts.keepTemp) {
      rmSync(workDir, { recursive: true, force: true });   // 跑完即弃——fixture 仓不留痕
    }
  }
}
